<?php
$SK_PAGE_ASSETS = [
    "<link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800&display=swap\" rel=\"stylesheet\">",
    "<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">",
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">",
    "<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">",
    "<script src=\"../../../../scricpt.js\"></script>",
];
include __DIR__ . '/../../../../header.php';
?>

<div class="background_main">
  <img src="../../../itinerary-placeholder-tour.svg" alt="Hyderabad">
</div>
<hr>
<div class="container-fluid" style="text-align: justify; width: 95%;">
  <h4>Hyderabad</h4>
  <p>
    Hyderabad combines heritage monuments, film-city attractions, temples, lakes, and family sightseeing. The three PDF routes are arranged below as 2N/3D, 3N/4D, and 4N/5D, and each route offers Basic, Standard, and Premium packages.
  </p>
</div>
<hr>

<div class="container" style="display: flex; justify-content: center;">
  <div class="row d-flex row_cards justify-content-center align-items-center">
    <div class="col-12 mb-3"><h4 class="text-center">2 Nights / 3 Days</h4></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">2 Nights / 3 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Basic Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad2N3DBasic.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">2 Nights / 3 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Standard Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Meal.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad2N3DStandard.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">2 Nights / 3 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Premium Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel4.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Meal.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad2N3DPremium.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>

    <div class="col-12 my-4"><h4 class="text-center">3 Nights / 4 Days</h4></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">3 Nights / 4 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Basic Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad3N4DBasic.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">3 Nights / 4 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Standard Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Meal.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad3N4DStandard.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">3 Nights / 4 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Premium Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel4.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Meal.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad3N4DPremium.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>

    <div class="col-12 my-4"><h4 class="text-center">4 Nights / 5 Days</h4></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">4 Nights / 5 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Basic Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad4N5DBasic.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">4 Nights / 5 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Standard Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Meal.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad4N5DStandard.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>
    <div class="col-lg-4 col-md-6 col-sm-12" style="display:flex; justify-content:center; align-items:center; margin:auto;"><div class="card"><div class="card-image" style="background-image: url(../../../itinerary-placeholder-tour.svg); background-size: cover;"><p style="background-color:#000080;">4 Nights / 5 Days</p></div><div class="card-content"><h5>GRAND SK Holidays-India-Hyderabad Premium Pack</h5><h4 class="card-title">Trip to Hyderabad</h4><hr><div class="vl"><div class="row d-flex align-items-start"><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Hotel4.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Meal.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Travel.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/sight-seeing.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Flight.png"></div><div class="col-2"><img src="<?php echo $SK_ROOT_PREFIX; ?>tours/Icons/Guide.png"></div></div></div><hr><div class="container d-flex justify-content-center"><a href="Itinerary/Hyderabad4N5DPremium.php"><button type="button" class="btn btn-primary" data-bs-toggle="modal">View Itinerary</button></a></div></div></div></div>
  </div>
</div>
<?php include __DIR__ . '/../../../../footer.php'; ?>